name: CI/CD Fake

on:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Build de Imagem Docker
        run: echo "Execução do comando de docker build"

      - name: Execução de Testes de Software
        run: echo "Aqui eu executo os testes de software"

      - name: Publicando a Release
        run: echo "Publicação da Release final"
  CD:
    needs: [CI]
    uses: rodrigogfreire/reaproveitamento-workflows/.github/workflows/cd.yaml@main
    with:
      ambiente: producao
    secrets:
      ambiente-entrega: ${{ secrets.AMBIENTE_ENTREGA }}